NO_PIE_CFLAG := $(shell $(CC) -fno-pie -x c /dev/null -c -o /dev/null >/dev/null 2>&1 && echo -fno-pie)
NO_PIE_LDFLAG := $(shell $(CC) -no-pie -x c /dev/null -o /dev/null >/dev/null 2>&1 && echo -no-pie)

nemu_CFLAGS_EXTRA := -ggdb3 -O2 $(NO_PIE_CFLAG)
$(eval $(call make_common_rules,nemu,$(nemu_CFLAGS_EXTRA)))

nemu_LDFLAGS := -lreadline $(NO_PIE_LDFLAG)

$(nemu_BIN): $(nemu_OBJS)
	$(call make_command, $(CC), $(nemu_LDFLAGS), ld $@, $^)
	$(call git_commit, "compile NEMU")


##### rules for generating some preprocessing results #####

PP_FILES := $(filter nemu/src/cpu/decode/%.c nemu/src/cpu/exec/%.c, $(nemu_CFILES))
PP_TARGET := $(PP_FILES:.c=.i)

.PHONY: $(PP_TARGET)

$(PP_TARGET): %.i: %.c
	$(call make_command, $(CC), -E -I$(nemu_INC_DIR), cc -E $<, $<)

cpp: $(PP_TARGET)

clean-cpp:
	-@rm -f $(PP_TARGET) 2> /dev/null
